### ISSUE TITLE
Notes are not able to download 

### ISSUE THREAD

**Issue by dx4iot** [tewarig/acm-app#2]
the notes uploaded in the app are not able to download

**Comment by tewarig** [comment]
that is the problem due to google drive, i will try to shift to shift this to other provider

**Comment by dx4iot** [comment]
> 
> 
> that is the problem due to google drive, i will try to shift to shift this to other provider

ya check it out !!

**Comment by tewarig** [comment]
finally this bug has been fixed, try to download notes in the new version
